apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # Additional annotations for Nginx
spec:
  rules:
    - host: {{ .Values.ingress.host | default "" | quote }}  # This allows using the IP directly if host is not specified
      http:
        paths:
          - path: /yaaf
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.service.port }}
