# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ .Release.Name }}
#   namespace: {{ .Values.namespace }}
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /yaaf
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /yaaf
#             pathType: Prefix
#             backend:
#               service:
#                 name: {{ .Release.Name }}
#                 port:
#                   number: {{ .Values.service.port }}
