replicaCount: 1

image:
  repository: acrinterview.azurecr.io/simple-web
  pullPolicy: IfNotPresent
  tag: "latest" # Or specific tag

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: "" # Or set domain name

namespace: yaaf
